<?php
/**
 * CoolMS2 Authentication module (http://www.coolms.com/)
 *
 * @link      http://github.com/coolms/authentication for the canonical source repository
 * @copyright Copyright (c) 2006-2015 Altgraphic, ALC (http://www.altgraphic.com)
 * @license   http://www.coolms.com/license/new-bsd New BSD License
 * @author    Dmitry Popov <d.popov@altgraphic.com>
 */

namespace CmsAuthentication;

// Set translation and namespace options here
$this->formLabel()->setTranslatorTextDomain(__NAMESPACE__);
$this->label()->setTranslatorTextDomain(__NAMESPACE__);
$this->formMessages()->setTranslatorTextDomain(__NAMESPACE__);
$this->formRow()->setTranslatorTextDomain(__NAMESPACE__);

// Set form fields classes and placeholders here
$form = $this->form;
$form->setAttributes(['class' => 'form-horizontal'])
    ->setLabelOption('twbs', [
        'element' => [
            'type' => 'label',
            'class' => 'panel-title',
        ],
        'icon' => [
            'type' => 'glyphicon',
            'content' => 'log-in',
            'placement' => 'prepend',
        ],
    ]);

$form->get('identity')->setOption('twbs', [
    'icon' => [
        'content' => 'user',
        'placement' => 'prepend',
    ],
]);

if ($form->has('rememberme')) {
    $form->get('rememberme')->setOption('twbs', [
        'row' => ['class' => 'pull-left'],
    ]);
}

$submit = $form->get('submit');
$submit->setAttributes(['value' => $form->getLabel() ?: 'Sign In'])
    ->setOption('twbs', [
        'element' => ['class' => 'btn-lg'],
    ]);

$form->prepare();

?>
<?= $this->form()->openTag($form); ?>
  <div class="panel panel-primary">
    <?php if($form->getLabel()): ?>
    <div class="panel-heading">
      <?= $this->formLabel($form); ?>
    </div>
    <?php endif; ?>
    <div class="panel-body">
      <?= $this->formMessages($form); ?>
      <?= $this->formRow($form->get('identity')); ?>
      <?= $this->formRow($form->get('credential')); ?>
      <div class="row">
        <div class="col-sm-12">
          <?php if ($form->has('rememberme')): ?>
            <?= $this->formRow($form->get('rememberme')); ?>
          <?php endif; ?>
          <p class="form-control-static pull-right">
            <?php if ($this->registrationRoute): ?>
<?php $links[] = <<<EOF
<a href="{$this->url($this->registrationRoute)}" title="{$this->translate('Sign Up', __NAMESPACE__)}">
  {$this->translate('Sign Up', __NAMESPACE__)}
</a>
EOF;
?>
            <?php endif; ?>
            <?php if ($this->resetCredentialRoute): ?>
<?php $links[] = <<<EOF
<a href="{$this->url($this->resetCredentialRoute)}" title="{$this->translate('Forgot credential?', __NAMESPACE__)}">
  {$this->translate('Forgot credential?', __NAMESPACE__)}
</a>
EOF;
?>
            <?php endif; ?>
            <?= isset($links) ? implode(' | ', $links) : '' ?>
          </p>
        </div>
      </div>
      <?= $this->formRow($form->get('redirect')); ?>
    </div>
    <div class="panel-footer clearfix">
      <?php if ($form->has('captcha')): ?>
        <?= $this->formRow($form->get('captcha')); ?>
      <?php endif; ?>
      <?php if ($form->has('csrf')): ?>
        <?= $this->formRow($form->get('csrf')); ?>
      <?php endif; ?>
      <?= $this->formRow($submit); ?>
    </div>
  </div>
<?= $this->form()->closeTag();
